apiVersion: v1
kind: Pod
metadata:
  label:
    test: yes
    env: test
  name: centos
spec:
  containers:
  - image: centos
    name: centos
    stdin: true
    tty: true

# kubectl run -i -t centos --image=centos
