apiVersion: v1
kind: Pod
metadata:
  name: kubia
  labels:
    name: kubia
    app: kubia
    version: 1
    env: test
spec:
  containers:
    - name: kubia
      image: luksa/kubia
      ports:
      - name: http
        containerPort: 8080

